language: node_js
node_js:
- stable
script:
- yarn test
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy_key
- ssh-add .travis/deploy_key
- git remote add deploy $DEPLOY_REPO
- git push deploy
- curl -o /tmp/travis-automerge https://raw.githubusercontent.com/cdown/travis-automerge/master/travis-automerge
- chmod a+x /tmp/travis-automerge
- BRANCHES_TO_MERGE_REGEX='^dev' BRANCH_TO_MERGE_INTO=master GITHUB_REPO=GerardVee/starter-kit
  /tmp/travis-automerge
env:
  global:
  - secure: HXz8hN7iLKmuqpp+lek4WCmYqwoGRqHtOPKy9snc5AC16lavGrehSweE9RzhKXZJyjw6pVRgBaeA/Z10xQFavnWEeA0AZKEEmxiOtNhRA922ZrMA1h0OBVbNUkFzkBZqfnP8WMb3yXDSrAoKiKbNxk4QQro8HjTJetar3ecWaH57b+Sp5DOCyWVxXIinfhySfGBvh8Q5TgM7zfsHfUIhX/bOzab1bpclmt2MGTJxMZG0CsslS5kXHyjsqNc1eA99aMftlmaUdxXfqMMFrVFN/0YhPwM/CFJ1uKGIJrlFBmfg1oSiHK5BT7nosdt4gfy5ZrdhJohIOYsv3B5XhZ31qDk0ciRfOMr8xw2YIp87Wu+H6rQA7wUq0WQFUATq5OTBn8N2fTDDfGbLMFH6Mm6UnLitL+KJ8eYtCn6mZNJwik7xNoVsXn9AeZ9X/iQFWra6b/mwKJbz7eb8C9neizvhQ0wqSHp2JJx5lPmgVCmPQqSIPuKHycwCeOPuZCjwEryUQPSP9eHglBSgHebn4pu/AvEPhhcf51MssjtimN1yyOgiwOAdWpCCSIdD8uVdmzy0J1LPc6lTJ+U7C+ijfs11Ml7nFnHcDb3vR0A+PdCVtNDNvrQU3wYBKiEHeY3szdp/Puwq3NWN9jRbbEa/LQ/4v2GllnS3jJYqpqpDuCE5UR8=
  - secure: BR+OomG/Pf3TwV/ChCcF4a30x8TZDwNxkvp54PFgV7YudkYPhpYuwZU63zX9YZwdc+TCQJtwFmx2jvGfT1fdivTMDl9n3bIY9RidMvBJ3ltMYV1dCsLF8ANONs47b8hrJLiQV0K+5aHaBAXcZAtppwD7ZNgCkNe/FYgIN9hp+aAtWqYjw2shrCBPedcksmvnYK9Nq3xLXoa3G0IuanGK/VdNmecOioJD4T91TUif0HM6N3l4lcw0py2d1cVjUdb+/JiLqHIaX8n2Pb0uymjos73fR2VPob45M/ivR+dIo5PARFS1clDSyEyKZ4EUVo6DCdaO8E5ruftQOTScEHLm4ad2NWShr/xA1O5HEDUWsQ5TRIyfRGYoGMbMmLynTP1i5ptTnKspm4AYcsLIjIoDpAaIcjhb22qz+GV/mgxLFi/ru7+SHdgTiZTEIJilQ8pxtBkHSlnL8ws0CpN6KL4d8apMHo8UUfYv+3p0EH8vCrJmLLDXhNROGCYcdklI+IFAeAA25pXJPt5p3deQqC/1tH+clKPK4m26bq2svGKW3fIi6iLEiqFxsL9EJoWKPu5VOzxRxS7ZC2pAgMhD7L+qrwADTmEjb4LHFU8ISVSmxIxfCsq1qs4jiHCF7YXvFCp0b2G6Qng7v1SlMvZBYKKn2IVKu4dCOVHSIMIUulVpr14=
