language: node_js
node_js:
- stable
before_install:
- openssl aes-256-cbc -K $encrypted_d33675411d26_key -iv $encrypted_d33675411d26_iv
  -in deploy_key.enc -out .travis/deploy_key -d
script:
- yarn test
after_success:
- bin/after_success
addons:
  ssh_known_hosts:
  - gerardvee.com
  - 107.170.197.76
env:
  global:
  - secure: m5sdumCLp8ExwD4Hq5DhrQxZO5iW/TMVJ/SavabM61NrCADBA/T9Hs1jrdR/PuQQZFmMJiuPxg8OiekRnodOsIDrSQ7ksn+aktidnHdyyKm5H4sI/ZSYnMymbFtigL7sfKAM3FsqsIj6/wCGwPZd5b0DXSLUuaoV/OFRSeEF+CL0MCIlEOZY8dPi2p8a605o7fN7lde4zeYlON6FDgToaxZPpNuBNrDiAvIHhM3dEa0BSumP3zSOO8oVCT/HolQooGEMl66KX/gBUln4N+UHg7McstMjaV/WIvwjKKRdpLc5MwbKPkJgK/6IJ+r3R8T54v44vani4oqq7C6QDqLTwu8xj6stsbmUneWBdqvwXFcInFxUmrjm93yLUSoS48SYJN/WPXKJMriKOkE2qMCz0XEx60j0UqsjPvs9aaVw6is4w9Qn+6gtRcc1Y17GstXoiq7lTalllSdm5hRJIwd+8JLgfKRfSqz1yGlwzobjsindkPpQwwNKI3AMGD5HJ1ORde+Ld5g7OhyvtpvmzNxW0wQmafreCRwUzbAh1JO8A44/o+J2LXhOwdloSHOwuhD3GIq0o2/aCNqtbxxAcIXX8hKuW6d+QlgMIIVIEBfAcGMWy5X8blSBlhUm5zFcECJgShvzYlDmdC46K1A4U404NezQvtX1XB1yxifCcrSWR94=
  - secure: COHUeMkvti5HlaiuRoyKk/Yc7Koxjqw41688TjLuOnlm8RdJBY6COf4JoF2vsmzbLbKJ76YfRiOYzA6/BX5CdeRHtw7nfHR52MiopImCgQoM+tjujQqYKc3EMBCl4MpfBx6pBIIH6qZCOARvJC8jM6Mmygj6CS6QTrtiDINS6A7FAlrTbMpxyADLLeag0pMJOg7/6TSshFOPH0wxWq3ZTqE2d7UUdnym9iVg5CGwERL8IwjXW8ohAlyr5ZAq6178jUY21OJ2tmhR4zYTXPMyTrc0fBHOeXcjiuOPtqqn0j+jxJ4fvGr7yb6JQaXKOxOp2YakWKgZmPp8vl3mRjiLJBgwlD3+c63tfLOTPIe1h0AiEvJxKjAoAFac+t9OcNUFkjPIdN02SnYjQf0RrebGwY3DYctyCrqzSGM111KKeoVlZ8fd1Jyqo+QKPEOUAvGq/nQQrsP7mpjpT0UJcIMJDjBZq8HNbF4ZVd96Bv0YjkYrpuIrc0AShcGgmSrFcvgZZKVHM3lgyiy0v9/ndlZ+t3oUCP8T5XC9B56cCY6dA/YREQfHGF2RlBpyKWysoqPsxmVEoAp4vHjvVWlc/dzl++YKLRKMoOTFTS/0WUjxuRQ5gzJQ/L7FoII7fcZTt6Z9HGXkHDPpN2xXiokFCJaDdombm4pxOfXuWPy6/6Ca3jQ=
