language: node_js
node_js:
- stable
before_install:
- openssl aes-256-cbc -K $encrypted_19d17ca168ea_key -iv $encrypted_19d17ca168ea_iv
  -in deploy_key.enc -out .travis/deploy_key -d
script:
- yarn test
after_success:
- bin/after_success
addons:
  ssh_known_hosts:
  - gerardvee.com
  - 107.170.197.76
env: