language: node_js
node_js:
- stable
before_install:
- openssl aes-256-cbc -K $encrypted_d33675411d26_key -iv $encrypted_d33675411d26_iv
  -in deploy_key.enc -out .travis/deploy_key -d
script:
- yarn test
after_success:
- bin/after_success
addons:
  ssh_known_hosts:
  - gerardvee.com
  - 107.170.197.76
#first one is ssh
env:
  global:
  - secure: QbFrxfF/28af9pdeGye4zYLDhe1pOxNd86T3CvVbo8UAbDOT8A/jHYZfKcrvKOok6JZcgJ7ZKgoRsnyUDHrI2E+Adommw8MerIYZA8S6gb0xUKLVmdqbRoJ69zWactpikzJRIsS+sRsuqR4qsEkhWIr91CMGHOoAxURQfcqM4P4b2ual8Rou/wd4WYPEiKA4r+gDVYLBC+e+AMU6iwBtE9Uq8sk4/fXNGgeywezFhnu3pHSBM6ZjcETxo7gQGbVAfxl3Jxt4WuAiZBBJTRgEaX48hbFslgtnxqxp3hKOvTJmDRPLbIQp88QZ9dY8mkBzQyWGR5ndQ7yAuvXSST1VgKYAKdCEi8t32YyH9cu8HUQKMldANJWwxpDNTuAEjOMkJfo0tL5Xn8eybqhzmQDHNbZp19udHZFcItwm5vOeVjlc6wySlZC6ndaoluthUGtC5sQmEKxJW11pSuCl/B+92XlN5rTZaU04d4e+EJPc5B5zIWhtRtnex7MzcHjW91MupRuW42x5Gqvi9DLnpJw1juxuymk2Str9UvbCl5cNbE+HWNuMvmSB/dAcwbpS6al3H4C/WaJsRdmBFQUPlOCDAYvtw3mgP+P7YE4JZiTBjl4ak5fzFZbgXJ4aVdQmA20wCrRJV70URXCCvbqvKBMKxlQPRY0EgljJxU53AdTdUjk=
  - secure: VuIA96MNb+yyHslo8TVCkh+sVgNcRbkYL2J3SCYVw5XjSPhFrTGdYTryqJWyRcvHMp1rX1zaxtGxALp3tXVz59FueyyIUfpfhBAFKKlYi5/P3C1etMUh+TxwUKhvOqAn81WmaG7jKy64VfdPNpwN9ctWLiR5xSTFWqHl69CxegvnFXwI7ahMUzs51rlTIlHo/tln/kIl4pMI5Q1W+V/KQeZXGFRzGY7E+2/OS9dL+K1GG5vS2XJ20sDqx7lF1THNnFIZGoLI8xS7XdoEAqbBj/F9vJojvmyy8MlxyWdO4d7qqFGHJDdIMJrteCGBHB9Q59GZpvoPb7B3JQAv1qQoPZFApyphkxC9QGuvts7HBW5WGh3qObSIcCk/EbN7MgKpL9oaynT/n6fsOhXhcFapL1cHqpC86vJs9NgOcrc4BvZx60SnhqbllKMGUX04k/U3wJoioBsufeyTtXCOyn/kMbsaWcYIBhlXm7dBrT8zcMaLACu3Q5wVOd0MxFoT/W6jR+HJSkLW2NhFVesj1spYUCyeas5QMPPQ/J3oyG6IMleF/Rz735jqajq0I4ts430fX6VTYzPahD2vx+1MNIInHS8PFFsvYkfK1LLwloFNPfNOXfuhUtTGNJkOwemXobaVkBPoOq6sGlRtDnh6XLLrjWHntOOfYSwuDK6dIHmwiUU=
