language: node_js
node_js:
- stable
before_install:
- openssl aes-256-cbc -K $encrypted_19d17ca168ea_key -iv $encrypted_19d17ca168ea_iv
  -in deploy_key.enc -out .travis/deploy_key -d
script:
- yarn test
after_success:
- bin/after_success
addons:
  ssh_known_hosts:
  - gerardvee.com
  - 107.170.197.76
env:
  global:
  - secure: pDjfcZphCW1e/XktaJnxdvvMEP+xYwQFt3gw2jaFaGgvmmgCkAe9efXqPfm+yK0jXojVaJwpu3fxSkAJs5JLl3XBIF1BusPyYXgDvaqjNNL/jDwocURlhKoCnkmMYBHy1v+SThHZTOt+nYnGmN/M8t0JMcTDv546AE1sVAN5EDbTLkrlznjFPpz2tVs5/WW1nqQIzVNQdY75gAxCdu1/A0X1zpRPz+A1FjgJlBsARDbrv5DxuDwrX+JM6Z7pJqNGoXz0y0Jiqp5yk1vPp6I8Ucl7qnVJgj3kkf52NCPtQXp5snuXzLwmbsLm1Bc0Ru/c6NUDQXjr/M3EvLWBm3POieTBQT8RWmzCg+rhyfxDemqfQZtKSBFmaDXv2lPnXeZPeLJmyxp/Y1RPX+7wZQNTui4D2IkiPIWpF0/BcQIQVtgQ8Yl4BMhdCGyh2ggTvnQQWAawkwJHKo5lLTSpqumYtcWDB2b5YkjF57HRLICFAQJ0ThflVq4JrSh66JmQ0x82TU6JUK51i1Qv/Xax/i0iYONB2qYNxrPBeXOEnWXrnq2hWY+QJPqtda1Xha3wor6iL0fr0Qji8usVFFgQaDR0JVA3p1FKaix0a1ohmZ0YeAn1VSm7/hH/9el12nXj1pDWkAxDPcT1Ym/iJigRbIqHKe4w0kuUDbeBRqFw3O+duVk=
  - secure: n3afXRuMtGaYsyf27Og+6LlIX+3K7W2UQswHEJcacQQMnU/MH7JxTSpBMgupK9/5Y9cmkiwIsy8hGvj8L7gh5eEBd1cUmP5OnpT0q0WhMpAV74MbQce2TlX7BPMulUW70N1c+7Xeu5FuVx9QONe5xIHcz3qFuKhprX7vk7EebnacVyjpCTkgHjQ//XEYnatB+FQFNFWfgkc0Py6xffqmJ9iZL3dLVb/ORvkLbrrSvGuK5rH1pxE3JVvEf4MWimErVU1yfR3qw/V0WHOogvUv2g+l2OUrQ5SzN7n6vl3Xm9J7KYnieMXmoPtnlpAyLvQPrng9LPXKdYDdVm+mqVanMN7ZZdJV/GLO+x7dDH2IOaxZ6lbdzpRz1gaBczJnCbQflemKEf/pYgTKzyxmi2Ub6GAy9AiYs3D7xgMauCd3uVrJ55qxnj2Aj5Y+sweHEbOFfhhHLe1PN4FVfHz1FWix9q+Bz82mwpg0lJ79EZg1AfsdaFS51zO70b+G5zr3YG/jzSnbBkI+4cjXTTBqC6asZezeb7nnH0uYT9DseI5Y/0Q9zwgSqyISObIv4bM8sv2k8UwKd0glwVcU2JBxGzFq7Q6cybBDApiA/AOmsfDQEBMDRLcxyWMtQLkBr627W5Wy8/yGyEEXig/e/McYVQxpbEv7hxQfv3zDTlqXanAPcE4=
