language: node_js
node_js:
- stable
before_install:
- openssl aes-256-cbc -K $encrypted_d33675411d26_key -iv $encrypted_d33675411d26_iv
  -in deploy_key.enc -out .travis/deploy_key -d
script:
- yarn test
after_success:
- bin/after_success
addons:
  ssh_known_hosts:
  - gerardvee.com
  - 107.170.197.76
env:
  global:
  - secure: VuIA96MNb+yyHslo8TVCkh+sVgNcRbkYL2J3SCYVw5XjSPhFrTGdYTryqJWyRcvHMp1rX1zaxtGxALp3tXVz59FueyyIUfpfhBAFKKlYi5/P3C1etMUh+TxwUKhvOqAn81WmaG7jKy64VfdPNpwN9ctWLiR5xSTFWqHl69CxegvnFXwI7ahMUzs51rlTIlHo/tln/kIl4pMI5Q1W+V/KQeZXGFRzGY7E+2/OS9dL+K1GG5vS2XJ20sDqx7lF1THNnFIZGoLI8xS7XdoEAqbBj/F9vJojvmyy8MlxyWdO4d7qqFGHJDdIMJrteCGBHB9Q59GZpvoPb7B3JQAv1qQoPZFApyphkxC9QGuvts7HBW5WGh3qObSIcCk/EbN7MgKpL9oaynT/n6fsOhXhcFapL1cHqpC86vJs9NgOcrc4BvZx60SnhqbllKMGUX04k/U3wJoioBsufeyTtXCOyn/kMbsaWcYIBhlXm7dBrT8zcMaLACu3Q5wVOd0MxFoT/W6jR+HJSkLW2NhFVesj1spYUCyeas5QMPPQ/J3oyG6IMleF/Rz735jqajq0I4ts430fX6VTYzPahD2vx+1MNIInHS8PFFsvYkfK1LLwloFNPfNOXfuhUtTGNJkOwemXobaVkBPoOq6sGlRtDnh6XLLrjWHntOOfYSwuDK6dIHmwiUU=
  - secure: ljRulh8kllE/ufozUtZOIOahtD3/OjGaEfnd15gsfetEmsydAHA1GdyH2MjyzkbUTt/CXuQWWTnqhdjhbL7K+797TNQWvEth/UvxC8dR7/M6PlOYWBKXR9cfY73KdWc8ZpnQAwx7MRlbSxaBiGkpSS+gF30omOiyFIZKVDQbW0UCcOkIUkQoAA3OsobCKO+H/z0ySfWTx6XFA1frRf7QuGMK1om11cA4AQCnw7wYXPgRDIkFQ5UmIcWk9o27iPCAHgRI+yzzowTgr2cm2ecbNAaRKX6VRMS2uOdvaFQ6dnrEmLKJ82hXM4tjHO8B9VIm5qou3CTTQGpTKtnfVRNT1jrvRqZVqrOq5+jLpsPwt2NUWISdkAZPhYOG7BVY5RI+iqs6B09GirVidkC1xlBVYriiNZsIncGkkMlCx9ZqyxGnCETs/ZhrxGo7lEhVnW6eP+D6zpCsaWDaZSM6kWyJ3h/ob0JgA3/4AzreSC+Eaujf9iQf/BlA9YrmFjhNZzHrTERQgKVybJNWJXsSrkVRoB/fQqD+mMixFY3JFLohlpIvbVzPdK+EQEmpE/aGPJv/El2Fok44oTcN0Ho89nx+/xRgb0VR6XSk0FYfPlyoVdSqSDPhra9cpAr1q56wdgdgof9doPxwv0nZgjGAwM6a2jSFu1q+esznYA+qXzYBEt8=
