language: node_js
node_js:
- stable
before_install:
- openssl aes-256-cbc -K $encrypted_d33675411d26_key -iv $encrypted_d33675411d26_iv
  -in deploy_key.enc -out .travis/deploy_key -d
script:
- yarn test
after_success:
- bin/after_success
addons:
  ssh_known_hosts:
  - gerardvee.com
  - 107.170.197.76
#last one is ssh
env:
  global:
  - secure: VuIA96MNb+yyHslo8TVCkh+sVgNcRbkYL2J3SCYVw5XjSPhFrTGdYTryqJWyRcvHMp1rX1zaxtGxALp3tXVz59FueyyIUfpfhBAFKKlYi5/P3C1etMUh+TxwUKhvOqAn81WmaG7jKy64VfdPNpwN9ctWLiR5xSTFWqHl69CxegvnFXwI7ahMUzs51rlTIlHo/tln/kIl4pMI5Q1W+V/KQeZXGFRzGY7E+2/OS9dL+K1GG5vS2XJ20sDqx7lF1THNnFIZGoLI8xS7XdoEAqbBj/F9vJojvmyy8MlxyWdO4d7qqFGHJDdIMJrteCGBHB9Q59GZpvoPb7B3JQAv1qQoPZFApyphkxC9QGuvts7HBW5WGh3qObSIcCk/EbN7MgKpL9oaynT/n6fsOhXhcFapL1cHqpC86vJs9NgOcrc4BvZx60SnhqbllKMGUX04k/U3wJoioBsufeyTtXCOyn/kMbsaWcYIBhlXm7dBrT8zcMaLACu3Q5wVOd0MxFoT/W6jR+HJSkLW2NhFVesj1spYUCyeas5QMPPQ/J3oyG6IMleF/Rz735jqajq0I4ts430fX6VTYzPahD2vx+1MNIInHS8PFFsvYkfK1LLwloFNPfNOXfuhUtTGNJkOwemXobaVkBPoOq6sGlRtDnh6XLLrjWHntOOfYSwuDK6dIHmwiUU=
  - secure: W8CIM9L17WHZIY9V/jDCy1KYPo7Ysc6RhrYI/N7eMWfIzH/pyWDeFKPc5KPm/6FZ0zc0Z8N/F8ntfLvneqwQUmdRkFxFmnLyuBxD+vnG8q4jLZz5uh6U1xV7zZuuOOMLcQ+oYoHxPR1NRLFsB1nUkIi1BXRvS0bir9mznXX46Xd3bj5LG1NBlAg31IYxklG5Pt33/LCx+6XK51p4HPvQK7+A5qg7q3Nw23XY/2wh44nGnIct+swIaf5UzcWZq9ZusBxkvm5Menpl9Ve2jhMWTzCTCBOGXkGR9d8FlSlfWXQhSX/LGEXC4JG6Thw/gYhHCFHVtOMmUCbYjl4aTj+VFs9N3bxw79IwPPf4UvVzhoEJYg90mp1moA195yller/tXfW8brK+d0YPXgFQkyA/UrSqtLb9HE7lHtdkSrps94Dz2L+RTbRj2gb7I3tflN/Mq5vdBX8cZBgeqpLYSoneMG7mH+e7dncguqcL+Ih1gSEQgw8UYuqZiIKy2ZAf6IpQJsbJiuH0JiYwtVhTuOFjNhLsHy53wjE4E0kpJpjukukUnCFa5oev0NPhz6PGH1OlNO47TdIwBFUDxBU+TNfjFPdxAENPcosRrREhMAM/9nVjGBY5MJ65WOlhjNW0T/qTcZGXe0o8MpUtIRTFsy47xS1SF5LF6KJS36P9CelvAbY=
